spring:
  thymeleaf:
    mode: HTML5
    cache: false
logging:
  level:
    org:
      springframework: error
server:
  port: ${port:8880}

# 记得替换成你的id和secret
wechat:
  appid: wxb051d9c24ff2e763
  secret: 89edc8fb31f188c7e727279d9b922bb4

# h2
db:
  url: jdbc:mysql://119.29.247.66:3306/db_book_manage?characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&useSSL=false
  username: root
  password: Liyong@123
  driver: com.mysql.jdbc.Driver