spring:
  thymeleaf:
    mode: HTML5
    cache: false
<<<<<<< HEAD
  #配置邮件通知服务    
  mail:
    host: smtp.qq.com
    username: 153342404@qq.com
    # 授权码
    password: tydcgkzyebnjcadf
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  activemq :
      broker-url : tcp://localhost:61616  
      in-memory : true  
      pool :
        enabled : false  
  data:
    mongodb:
      host : 127.0.0.1
      port : 27017
      database: jesper   
logging:
  level:
    org:
      springframework: error
server:
  port: ${port:8888}

# lsof -i :8880  查看端口占用    kill 8880 杀掉某个端口
# 部署命令  nohup Java -jar xxxxxx.jar &
# usr/local/nginx/sbin   ./nginx -s reload
# 记得替换成你的id和secret
wechat:
  appid: wxb051d9c24ff2e763
  secret: 89edc8fb31f188c7e727279d9b922bb4

# h2
db:
  url: jdbc:mysql://119.29.247.66:3306/db_book_manage?characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&useSSL=false
  username: root
  password: Liyong@123
  driver: com.mysql.jdbc.Driver

 
=======
logging:
  level:
    org:
      springframework: error
server:
  port: ${port:8880}

# 记得替换成你的id和secret
wechat:
  appid: wxb051d9c24ff2e763
  secret: 89edc8fb31f188c7e727279d9b922bb4

# h2
db:
  url: jdbc:mysql://119.29.247.66:3306/db_book_manage?characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&useSSL=false
  username: root
  password: Liyong@123
  driver: com.mysql.jdbc.Driver
>>>>>>> branch 'master' of https://github.com/liyong7686/mall.git
