spring:
  #配置html页面模板
  thymeleaf:
    mode: HTML5
    cache: false
  #配置邮件通知服务    
  mail:
    host: smtp.qq.com
    username: 153342404@qq.com
    # 授权码
    password: tydcgkzyebnjcadf
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  #配置   activemq 消息插件       
  activemq :
      broker-url : tcp://localhost:61616  
      in-memory : true  
      pool :
        enabled : false  
  #配置 mongodb 文件存储插件
  data:
    mongodb:
      host : 127.0.0.1
      port : 27017
      database: jesper 
  #配置   redis 缓存数据库
  redis:
    host: 127.0.0.1
    port: 6379 
    password : $LY201514P
    database: 0 
    timeout : 3000
    pool:
        max-active: 8
        max-wait: 1000
        max-idle: 8 
        min-idle: 0      
logging:
  level:
    org:
      springframework: error
server:
  port: ${port:8888}

# lsof -i :8880  查看端口占用    kill 8880 杀掉某个端口
# 部署命令  nohup Java -jar xxxxxx.jar &
# usr/local/nginx/sbin   ./nginx -s reload
# 记得替换成你的id和secret
wechat:
  appid: wxb051d9c24ff2e763
  secret: 89edc8fb31f188c7e727279d9b922bb4

# 配置mysql 数据库
db:
  url: jdbc:mysql://119.29.247.66:3306/db_book_manage?characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&useSSL=false
  username: root
  password: Liyong@123
  driver: com.mysql.jdbc.Driver

